[platformio]
default_envs = megaatmega2560

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
test_framework = unity
test_build_src = true
upload_port = /dev/ttyUSB0
test_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
monitor_speed = 115200
lib_deps =
  miguelbalboa/MFRC522 @ ^1.4.12
  arduino-libraries/Servo @ ^1.2.2
  chris--a/Keypad @ ^3.1.1
  https://github.com/johnrickman/LiquidCrystal_I2C.git
